remove parallel

diff --git a/ci/Junit/JenkinsFile b/ci/Junit/JenkinsFile
--- a/ci/Junit/JenkinsFile
+++ b/ci/Junit/JenkinsFile
@@ -2,10 +2,38 @@
 
 pipeline {
 	agent any
-
-	def tasks = [:]
-
-	tasks["HBase Tests"] = {
+	stages {
+		stage('Accumulo Tests') {
+			steps {
+				sh '''
+					code=0
+					{
+						export db_type="accumulo"
+						source ci/createcluster.sh &&
+						code=0
+						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/startup.sh &&
+						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/runtests_accumulo.sh  &&
+						remoteHOSTNAME=$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/getHOSTNAME.sh) &&
+						sudo npm install newman --global &&
+						PATH=$(npm bin):$PATH newman run ci/Postman/collections/Geowave_Happypath.postman_collection.json \
+							-e ci/Postman/environments/gw_hbase.postman_environment.json \
+							--timeout-request 60000 \
+							--global-var "domain=${DOMAIN}" \
+							--global-var "hostname=${remoteHOSTNAME}"
+					} || {
+						code=1
+					}
+					aws emr terminate-clusters --cluster-ids ${CLUSTER_ID} --region ${REGION}
+					exit $code
+				'''
+			}
+			post {
+				failure {
+					echo "* ! > ! * This should be sending a slack failure * ! < ! *"
+					// slackSend color: 'danger', message: ':fire: The accumulo acceptance tests have failed :fire:'
+				}
+			}
+		}
 		stage('HBase Tests') {
 			steps {
 				sh '''
@@ -38,40 +66,4 @@ pipeline {
 			}
 		}
 	}
-
-	tasks["Accumulo Tests"] = {
-		stage('Accumulo Tests') {
-			steps {
-				sh '''
-					code=0
-					{
-						export db_type="accumulo"
-						source ci/createcluster.sh &&
-						code=0
-						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/startup.sh &&
-						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/runtests_accumulo.sh  &&
-						remoteHOSTNAME=$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/getHOSTNAME.sh) &&
-						sudo npm install newman --global &&
-						PATH=$(npm bin):$PATH newman run ci/Postman/collections/Geowave_Happypath.postman_collection.json \
-							-e ci/Postman/environments/gw_hbase.postman_environment.json \
-							--timeout-request 60000 \
-							--global-var "domain=${DOMAIN}" \
-							--global-var "hostname=${remoteHOSTNAME}"
-					} || {
-						code=1
-					}
-					aws emr terminate-clusters --cluster-ids ${CLUSTER_ID} --region ${REGION}
-					exit $code
-				'''
-			}
-			post {
-				failure {
-					echo "* ! > ! * This should be sending a slack failure * ! < ! *"
-					// slackSend color: 'danger', message: ':fire: The accumulo acceptance tests have failed :fire:'
-				}
-			}
-		}
-	}
-
-	parallel tasks
 }
