try/catch with slack send

diff --git a/ci/Junit/JenkinsFile b/ci/Junit/JenkinsFile
--- a/ci/Junit/JenkinsFile
+++ b/ci/Junit/JenkinsFile
@@ -5,28 +5,31 @@ pipeline {
 	stages {
 		stage('HBase Tests') {
 			steps{
-				slackSend color: 'good', message: 'in ur pipeline, spamming ur slack'
-				sh '''
-				export db_type="hbase"
-				source ci/createcluster.sh
-				code=0
-				{
-					ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/startup.sh
-					ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/runtests_hbase.sh
-					curl ${DOMAIN}:8000/restservices/api
-					npm install newman --global
-					PATH=$(npm bin):$PATH newman run ci/Postman/collections/Geowave_Happypath.postman_collection.json \
-						-e ci/Postman/environments/gw_hbase.postman_environment.json \
-						--timeout-request 10000 \
-						--global-var "domain=${DOMAIN}"
-				} || {
-					echo "there was a failure"
-					code=1 
+				try {
+					sh '''
+						export db_type="hbase"
+						source ci/createcluster.sh
+						code=0
+						{
+							ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/startup.sh
+							ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/runtests_hbase.sh
+							curl ${DOMAIN}:8000/restservices/api
+							npm install newman --global
+							PATH=$(npm bin):$PATH newman run ci/Postman/collections/Geowave_Happypath.postman_collection.json \
+								-e ci/Postman/environments/gw_hbase.postman_environment.json \
+								--timeout-request 10000 \
+								--global-var "domain=${DOMAIN}"
+						} || {
+							echo "there was a failure"
+							code=1 
+						}
+						aws emr terminate-clusters --cluster-ids ${CLUSTER_ID} --region ${REGION}
+						exit $code
+					'''
 				}
-				aws emr terminate-clusters --cluster-ids ${CLUSTER_ID} --region ${REGION}
-				exit $code
-				'''
-				slackSend color: 'bad', message: 'does this message get sent?'
+				catch (e) {
+					slackSend color: 'bad', message: ':fire: The hbase acceptance tests have failed :fire:'
+				}
 			}
 		}
 		stage('Accumulo Tests') {
