accumulo first

diff --git a/ci/Junit/JenkinsFile b/ci/Junit/JenkinsFile
--- a/ci/Junit/JenkinsFile
+++ b/ci/Junit/JenkinsFile
@@ -3,6 +3,43 @@
 pipeline {
 	agent any
 	stages {
+		stage('Accumulo Tests') {
+			steps {
+				sh '''
+					export db_type="accumulo"
+					source ci/createcluster.sh
+					code=0
+					{
+						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/startup.sh
+						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/runtests_accumulo.sh
+						remoteHOSTNAME=$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/getHOSTNAME.sh)
+						npm install newman --global
+						PATH=$(npm bin):$PATH newman run ci/Postman/collections/Geowave_Happypath.postman_collection.json \
+							-e ci/Postman/environments/gw_hbase.postman_environment.json \
+							--timeout-request 10000 \
+							--global-var "domain=${DOMAIN}" \
+							--global-var "hostname=${remoteHOSTNAME}"
+					} || {
+						echo "there was a failure"
+						code=1 
+					}
+					aws emr terminate-clusters --cluster-ids ${CLUSTER_ID} --region ${REGION}
+					exit $code
+				'''
+			}
+			post {
+				failure {
+					slackSend color: 'danger', message: ':fire: The accumulo acceptance tests have failed :fire:'
+				}
+				changed {
+					script {
+						if (currentBuild.currentResult == 'SUCCESS') {
+							slackSend color: 'good', message: ':unicorn_face: The accumulo acceptance tests are passing again! :unicorn_face:'
+						}
+					}
+				}
+			}
+		}
 		stage('HBase Tests') {
 			steps {
 				sh '''
@@ -13,11 +50,10 @@ pipeline {
 						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/startup.sh
 						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/runtests_hbase.sh
 						remoteHOSTNAME=$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/getHOSTNAME.sh)
-						curl ${DOMAIN}:8000/restservices/api
 						npm install newman --global
 						PATH=$(npm bin):$PATH newman run ci/Postman/collections/Geowave_Happypath.postman_collection.json \
 							-e ci/Postman/environments/gw_hbase.postman_environment.json \
-							--timeout-request 60000 \
+							--timeout-request 10000 \
 							--global-var "domain=${DOMAIN}" \
 							--global-var "hostname=${remoteHOSTNAME}"
 					} || {
@@ -36,41 +72,6 @@ pipeline {
 					script {
 						if (currentBuild.currentResult == 'SUCCESS') {
 							slackSend color: 'good', message: ':unicorn_face: The hbase acceptance tests are passing again! :unicorn_face:'
-						}
-					}
-				}
-			}
-		}
-		stage('Accumulo Tests') {
-			steps{
-				sh '''
-					export db_type="accumulo"
-					source ci/createcluster.sh
-					code=0
-					{
-						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/startup.sh
-						ssh -o StrictHostKeyChecking=no -i ~/.ssh/${KEYNAME}.pem hadoop@${DOMAIN} < ci/runtests_accumulo.sh
-						npm install newman --global
-						PATH=$(npm bin):$PATH newman run ci/Postman/collections/Geowave_Happypath.postman_collection.json \
-							-e ci/Postman/environments/gw_hbase.postman_environment.json \
-							--timeout-request 10000 \
-							--global-var "domain=${DOMAIN}"
-					} || {
-						echo "there was a failure"
-						code=1 
-					}
-					aws emr terminate-clusters --cluster-ids ${CLUSTER_ID} --region ${REGION}
-					exit $code
-				'''
-			}
-			post {
-				failure {
-					slackSend color: 'danger', message: ':fire: The accumulo acceptance tests have failed :fire:'
-				}
-				changed {
-					script {
-						if (currentBuild.currentResult == 'SUCCESS') {
-							slackSend color: 'good', message: ':unicorn_face: The accumulo acceptance tests are passing again! :unicorn_face:'
 						}
 					}
 				}
